<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
<?php
$localhost='localhost';
$username='prueba1';
$password='1234';
$database='prueba';
?>
